export const collectionDefinitions = [
  {
    key: 'parish_profile',
    label: 'História da Paróquia',
    description: 'Conteúdo institucional, endereço e galeria da matriz.',
    table: 'parish_profile',
    titleField: 'title',
    slugField: 'slug',
    order: [{ field: 'updated_at', direction: 'desc' }],
    sortable: false,
    fields: [
      { name: 'title', label: 'Título', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', required: true },
      { name: 'subtitle', label: 'Subtítulo', type: 'text' },
      { name: 'content', label: 'Conteúdo', type: 'textarea', required: true },
      { name: 'address', label: 'Endereço', type: 'text' },
      { name: 'google_maps_url', label: 'Link do Google Maps', type: 'url' },
      { name: 'latitude', label: 'Latitude', type: 'number' },
      { name: 'longitude', label: 'Longitude', type: 'number' },
      { name: 'gallery', label: 'Galeria', type: 'gallery', help: 'Separe por linha. Mais de 5 imagens gera alerta de performance.' },
      { name: 'is_published', label: 'Publicado', type: 'checkbox' },
    ],
  },
  {
    key: 'communities',
    label: 'Comunidades',
    description: 'Cadastro de comunidades com mapa, história e fotos.',
    table: 'communities',
    titleField: 'name',
    slugField: 'slug',
    order: [{ field: 'manual_order', direction: 'asc' }, { field: 'created_at', direction: 'desc' }],
    sortable: true,
    fields: [
      { name: 'name', label: 'Nome', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', required: true },
      { name: 'summary', label: 'Resumo', type: 'textarea' },
      { name: 'story', label: 'História', type: 'textarea' },
      { name: 'address', label: 'Endereço', type: 'text' },
      { name: 'google_maps_url', label: 'Link do Google Maps', type: 'url' },
      { name: 'latitude', label: 'Latitude', type: 'number' },
      { name: 'longitude', label: 'Longitude', type: 'number' },
      { name: 'cover_image_url', label: 'Imagem de capa', type: 'text' },
      { name: 'gallery', label: 'Galeria', type: 'gallery', help: 'Mais de 5 imagens exibe alerta de peso/performance.' },
      { name: 'manual_order', label: 'Ordem', type: 'number' },
      { name: 'is_published', label: 'Publicado', type: 'checkbox' },
    ],
  },
  {
    key: 'clergy',
    label: 'Clero',
    description: 'Padres e diáconos com ordenação manual e status atual.',
    table: 'clergy',
    titleField: 'name',
    order: [{ field: 'manual_order', direction: 'asc' }, { field: 'created_at', direction: 'desc' }],
    sortable: true,
    fields: [
      { name: 'name', label: 'Nome', type: 'text', required: true },
      { name: 'role', label: 'Função', type: 'select', required: true, options: ['pároco', 'vigário', 'diácono'] },
      { name: 'bio', label: 'Descrição breve', type: 'textarea' },
      { name: 'photo_url', label: 'Foto', type: 'text' },
      { name: 'is_current', label: 'Atual', type: 'checkbox' },
      { name: 'manual_order', label: 'Ordem', type: 'number' },
    ],
  },
  {
    key: 'news',
    label: 'Notícias',
    description: 'Publicações da paróquia com data e galeria.',
    table: 'news',
    titleField: 'title',
    slugField: 'slug',
    order: [{ field: 'published_at', direction: 'desc' }, { field: 'created_at', direction: 'desc' }],
    sortable: false,
    fields: [
      { name: 'title', label: 'Título', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', required: true },
      { name: 'summary', label: 'Resumo', type: 'textarea' },
      { name: 'content', label: 'Conteúdo', type: 'textarea', required: true },
      { name: 'category', label: 'Categoria', type: 'text' },
      { name: 'cover_image_url', label: 'Imagem de capa', type: 'text' },
      { name: 'gallery', label: 'Galeria', type: 'gallery', help: 'Mais de 5 imagens gera alerta de performance.' },
      { name: 'published_at', label: 'Data de publicação', type: 'date' },
      { name: 'is_published', label: 'Publicado', type: 'checkbox' },
    ],
  },
  {
    key: 'mass_schedules',
    label: 'Horários de Missa',
    description: 'Missas com local, dia e faixa de horário.',
    table: 'mass_schedules',
    titleField: 'title',
    order: [{ field: 'manual_order', direction: 'asc' }, { field: 'created_at', direction: 'desc' }],
    sortable: true,
    fields: [
      { name: 'title', label: 'Título', type: 'text', required: true },
      { name: 'day_label', label: 'Dia', type: 'text', required: true },
      { name: 'time_label', label: 'Horário', type: 'text', required: true },
      { name: 'location', label: 'Local', type: 'text' },
      { name: 'category', label: 'Categoria', type: 'select', options: ['missa', 'celebração', 'comunidade'] },
      { name: 'manual_order', label: 'Ordem', type: 'number' },
      { name: 'is_published', label: 'Publicado', type: 'checkbox' },
    ],
  },
  {
    key: 'office_hours',
    label: 'Atendimento Paroquial',
    description: 'Horários de secretaria e atendimento.',
    table: 'office_hours',
    titleField: 'title',
    order: [{ field: 'manual_order', direction: 'asc' }, { field: 'created_at', direction: 'desc' }],
    sortable: true,
    fields: [
      { name: 'title', label: 'Título', type: 'text', required: true },
      { name: 'day_label', label: 'Dia', type: 'text', required: true },
      { name: 'hours_label', label: 'Horário', type: 'text', required: true },
      { name: 'manual_order', label: 'Ordem', type: 'number' },
      { name: 'is_published', label: 'Publicado', type: 'checkbox' },
    ],
  },
  {
    key: 'useful_links',
    label: 'Links Úteis',
    description: 'Links externos organizados por categoria.',
    table: 'useful_links',
    titleField: 'title',
    order: [{ field: 'manual_order', direction: 'asc' }, { field: 'created_at', direction: 'desc' }],
    sortable: true,
    fields: [
      { name: 'title', label: 'Título', type: 'text', required: true },
      { name: 'url', label: 'URL', type: 'url', required: true },
      { name: 'description', label: 'Descrição', type: 'textarea' },
      { name: 'category', label: 'Categoria', type: 'text', required: true },
      { name: 'manual_order', label: 'Ordem', type: 'number' },
      { name: 'open_in_new_tab', label: 'Abrir em nova aba', type: 'checkbox' },
      { name: 'is_published', label: 'Publicado', type: 'checkbox' },
    ],
  },
  {
    key: 'liturgy_links',
    label: 'Links da Liturgia',
    description: 'Atalhos para liturgia diária e santo do dia.',
    table: 'liturgy_links',
    titleField: 'title',
    order: [{ field: 'manual_order', direction: 'asc' }, { field: 'created_at', direction: 'desc' }],
    sortable: true,
    fields: [
      { name: 'title', label: 'Título', type: 'text', required: true },
      { name: 'url', label: 'URL', type: 'url', required: true },
      { name: 'description', label: 'Descrição', type: 'textarea' },
      { name: 'manual_order', label: 'Ordem', type: 'number' },
      { name: 'open_in_new_tab', label: 'Abrir em nova aba', type: 'checkbox' },
      { name: 'is_published', label: 'Publicado', type: 'checkbox' },
    ],
  },
  {
    key: 'pastorals',
    label: 'Pastorais',
    description: 'Grupos de serviço, movimentos e ações sociais.',
    table: 'pastorals',
    titleField: 'title',
    order: [{ field: 'manual_order', direction: 'asc' }, { field: 'created_at', direction: 'desc' }],
    sortable: true,
    fields: [
      { name: 'title', label: 'Título', type: 'text', required: true },
      { name: 'description', label: 'Descrição', type: 'textarea' },
      { name: 'image_url', label: 'Imagem', type: 'text' },
      { name: 'manual_order', label: 'Ordem', type: 'number' },
      { name: 'is_published', label: 'Publicado', type: 'checkbox' },
    ],
  },
  {
    key: 'pages',
    label: 'Páginas institucionais',
    description: 'Conteúdo simples para casamentos, oração e afins.',
    table: 'pages',
    titleField: 'title',
    slugField: 'slug',
    order: [{ field: 'updated_at', direction: 'desc' }],
    sortable: false,
    fields: [
      { name: 'title', label: 'Título', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', required: true },
      { name: 'page_key', label: 'Chave', type: 'text', required: true },
      { name: 'content', label: 'Conteúdo', type: 'textarea' },
      { name: 'is_published', label: 'Publicado', type: 'checkbox' },
    ],
  },
  {
    key: 'social_links',
    label: 'Redes sociais',
    description: 'Perfis oficiais e posições do rodapé.',
    table: 'social_links',
    titleField: 'network',
    order: [{ field: 'manual_order', direction: 'asc' }, { field: 'created_at', direction: 'desc' }],
    sortable: true,
    fields: [
      { name: 'network', label: 'Rede', type: 'text', required: true },
      { name: 'url', label: 'URL', type: 'url', required: true },
      { name: 'icon', label: 'Ícone', type: 'text' },
      { name: 'manual_order', label: 'Ordem', type: 'number' },
      { name: 'is_published', label: 'Publicado', type: 'checkbox' },
    ],
  },
];

export const collectionByKey = Object.fromEntries(collectionDefinitions.map((definition) => [definition.key, definition]));

export const adminQuickLinks = collectionDefinitions.map(({ key, label, description }) => ({ key, label, description }));